### ISSUE TITLE
Nether portal bounces player outside Nether's world border if they are in survival.

### ISSUE THREAD

**Issue by Routhinator** [LemADEC/WarpDrive#418]
**Describe the bug**
When this mod is added to a modpack, anyone opening going through a nether portal that's been opened more than 1000 blocks from spawn, while in survival mode, is bounced out of the nether's world border and dies. Creative mode works around this.

Removing warp drive from our modpacks has fixed this behaviour. We did this after noticing the nether behaviour change that was added in August.

There's not much info I can give you as there was no errors. 

**Versions** (latest is not a valid answer)
 - WarpDrive version: 1.5.11
 - Forge version: 14.23.5.2847
 - Modpack name/version: Multifarious Quest 2020, Space Race 2019 - these are new custom modpacks. 
 - Other notable mods & version: 

Packmaker mods list from MQ 2020 Please ask if any versions are needed as there is a lot to list.

```
mods:
  - ae2-stuff:
  - ae2-wireless-terminal-library:
  - ae2wtlib:
  - angel-ring-to-bauble:
  - angry-pixel-the-betweenlands-mod:
  - appleskin:
  - applied-energistics-2:
  - armory-expansion:
  - aroma1997core:
  - aroma1997s-dimensional-world:
  - asmodeuscore:
  - astral-sorcery:
  - autoreglib:
  - atomic-science:
  - backpacks:
  - back-tools:
  - bad-wither-no-cookie-reloaded:
  - base:
  - base-metals:
  - baubley-heart-canisters:
  - bdlib:
  - baubles:
  - bed-bugs:
  - better-builders-wands:
  - better-advancements:
      clientonly: true
  - betterfps:
  - bibliocraft:
  - biomes-o-plenty:
  - blockcraftery:
  - blur:
      clientonly: true
  - bookshelf:
  - botania:
  - building-gadgets:
  - brandons-core:
  - btfu-continuous-rsync-incremental-backup:
      serveronly: true
  - cavern:
  - chameleon:
  - charset-lib:
  - chest-transporter:
  - chickens:
  - chicken-chunks-1-8:
  - chisel:
  - clumps:
  - cofh-core:
  - cofh-world:
  - codechicken-lib-1-8:
  - contenttweaker:
  - compact-machines:
  - common-capabilities:
  - controlling:
      clientonly: true
  - constructs-armory:
  - cooking-for-blockheads:
  - corail-pillar:
  - corail-pillar-extension-chisel:
  - corail-pillar-extension-quark:
  - cosmetic-armor-reworked:
  - crafttweaker:
  - ctm:
      clientonly: true
  - cucumber:
  - custom-main-menu:
      clientonly: true
  - cyclops-core:
  - dank-null:
  - dark-utilities:
  - default-options:
  - defiled-lands:
  - deep-resonance:
  - default-world-generator-port:
  - diet-hoppers:
  - draconic-evolution:
  - eleccore:
  - elemental-dimensions:
  - endertweaker:
  - endercore:
  - ender-io:
  - ender-io-endergy:
  - ender-storage-1-8:
  - energy-converters:
  - engineers-decor:
  - engineers-doors:
  - environmental-materials:
  - environmental-tech:
  - exchangers:
  - extra-glass:
  - extraplanets:
  - et-lunar-environmental-tech-addon:
  - exchangers:
  - extended-crafting:
  - extracells2:
  - extreme-reactors:
  - fairy-lights:
  - fast-leaf-decay:
  - fastworkbench:
  - forestry:
  - forgeendertech:
  - flux-networks:
  - foamfix-for-minecraft:
  - forge-multipart-cbe:
  - ftblib:
  - ftb-utilities:
  - funky-locomotion:
  - galacticrafttweaker:
  - galacticraft-add-on-more-planets:
  - gendustry:
  - gendustry-jei-addon:
  - gotta-go-fast:
  - gravestone-mod:
  - gravity-gun:
  - guide-api:
  - hammer-lib:
  - hunting-dimension:
  - ichunutil:
  - ice-and-fire-dragons:
  - immersive-engineering:
  - immersive-petroleum:
  - immersive-tech:
  - industrial-foregoing:
  - ingame-info-xml:
  - instantunify:
  - initial-inventory:
  - integration-foregoing:
  - integrated-crafting:
  - integrated-dynamics:
  - integrated-terminals:
  - integrated-tunnels:
  - inventory-tweaks:
  - iron-chests:
  - ivtoolkit:
  - jei:
  - jei-bees:
  - jeid:
  - journeymap:
  - just-a-few-fish:
  - just-enough-harvestcraft:
      clientonly: true
  - just-enough-resources-jer:
      clientonly: true
  - kleeslabs:
  - laggoggles:
  - lemonlib:
  - libvulpes:
  - light-level-overlay-reloaded:
      clientonly: true
  - lost-souls:
  - llibrary:
  - lunatriuscore:
  - malisiscore:
  - malisisdoors:
  - mantle:
  - mcjtylib:
  - mchorses-mclib:
  - metamorph:
  - mmdlib:
  - mjrlegendslib:
  - modular-powersuits:
  - more-bees:
  - mob-grinding-utils:
  - mod-name-tooltip:
      clientonly: true
  - modtweaker:
  - modular-routers:
  - more-chickens:
  - mouse-tweaks:
      clientonly: true
  - mrcrayfish-furniture-mod:
  - mrtjpcore:
  - mtlib:
  - mysticallib:
  - natura:
  - natures-compass:
  - nuclearcraft-mod:
  - numina:
  - oc-xnet-driver:
  - openblocks:
  - opencomputers:
  - openfm:
  - openmodslib:
  - ore-excavation:
  - orelib:
  - p455w0rds-library:
  - pams-harvestcraft:
  - placebo:
  - prefab:
  - pretty-beaches:
  - project-red-base:
  - project-red-lighting:
  - ptrlib:
  - plustic:
  - quark:
  - randompatches:
  - randomtweaks:
  - reauth:
      clientonly: true
  - realistic-terrain-generation:
  - reborncore:
  - recurrent-complex:
  - redstone-arsenal:
  - redstone-flux:
  - reliquary-v1-3:
  - resource-loader:
      clientonly: true
  - rftools:
  - rftools-control:
  - rftools-dimensions:
  - rftools-power:
  - rftools-power-oc-integration:
  - roost:
  - sanlib:
  - scannable:
  - shadowfacts-forgelin:
  - silent-lib:
  - simple-void-world:
  - simply-jetpacks-2:
  - smooth-font:
  - sonar-core:
  - statues-rechiseled:
  - steves-carts-reborn:
  - stevekungs-lib:
  - stimmedcow-nomorerecipeconflict:
  - stones-bricks-missing-vanilla-blocks:
  - storage-drawers:
  - storage-drawers-extras:
  - tesla-core-lib:
  - thaumcraft:
  - thaumcraft-inventory-scanning:
  - thaumic-additions:
  - thaumic-augmentation:
  - thaumic-energistics:
  - thaumic-jei:
  - thaumic-periphery:
  - the-one-probe:
  - the-twilight-forest:
  - the-beneath:
  - the-lost-cities:
  - thermal-cultivation:
  - thermal-dynamics:
  - thermal-expansion:
  - thermal-foundation:
  - thermal-innovation:
  - tickprofiler:
  - tinkers-complement:
  - tinkers-construct:
  - tinkers-tool-leveling:
  - toast-control:
      clientonly: true
  - top-addons:
  - torchmaster:
  - unidict:
  - unlimited-chisel-works:
  - wanionlib:
  - waystones:
  - wireless-crafting-terminal:
  - woot:
  - valkyrielib:
  - vanillatweaks:
  - xnet:
  - yabba:
  - ynot:
  - zerocore:

```
